//common
export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';


//agendaList
export const GET_AGENDALIST = 'GET_AGENDALIST';



//agenda
export const AGENDA_UPDATE_FIELD = 'AGENDA_UPDATE_FIELD';
export const AGENDA_CREATE = 'AGENDA_CREATE';
export const AGENDA_UPDATE = 'AGENDA_UPDATE';
export const AGENDA_SAVE = 'AGENDA_SAVE';
export const AGENDA_CLOSE_DIALOG = 'AGENDA_CLOSE_DIALOG';
export const AGENDA_MENU_ITEM_TAP = 'AGENDA_MENU_ITEM_TAP';
export const AGENDA_GET_DETAIL = 'AGENDA_GET_DETAIL';


//auth
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';

//agendaItem
export const AI_ACTION_MOUSE_OVER = 'AI_ACTION_MOUSE_OVER';
export const AI_ACTION_MOUSE_OUT = 'AI_ACTION_MOUSE_OUT';
export const AI_ACTION_NAV_DETAIL = 'AI_ACTION_NAV_DETAIL';

//agendaPlay
export const AP_ACTION_GET_DETAIL = 'AP_ACTION_GET_DETAIL';
export const AP_ACTION_UPDATE_TIMER = 'AP_ACTION_UPDATE_TIMER';
export const AP_ACTION_UPDATE_CLOCK = 'AP_ACTION_UPDATE_CLOCK';

//header
export const H_ACTION_TOGGLE = 'H_ACTION_TOGGLE';


